config/routes.rb
Zeenatlabaw::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  devise_for :users

    resources :reports do
      collection do
        post 'download' 
        get 'report'
      end
    end

  root :to => 'reports#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :rep_id, :file

  mount_uploader :file, FileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username,:email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def index
	end

	def new
		@report = Report.new
	end

	def create
		@report = Report.new(params[:report])
		@report.save!
		flash[:success] = "Report successfully saved."
		redirect_to reports_path
	end

	def report
		@report = Report.new
	end

	def download
    	@report = Report.find_by_rep_id(params[:report][:rep_id])
    	if @report
    		send_file @report.file.path, :filename => @report.rep_id
		else
			flash[:error] = "Please enter correct report id."
			redirect_to :back
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_content.html.erb
<% flash.each do |name, msg| %>
     <div class="alert alert-<%= name %>">
     <a class="close" data-dismiss="alert">×</a>
     <%= msg %>
   </div>
<% end %>
<div class="content">
        <div class="row-fluid ">
          <div class="span12">
            <%= yield %>
          </div>
        </div><!--/row-->
      </div><!--/content-->

app/views/layouts/_navBarLayout.html.erb
<div class="navbar navbar-static-top">

  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Zeenat Lab Arifwala", root_path, class: "brand" %>

        <div class="nav-collapse">
          <ul class="nav pull-right">
            <% if current_user %>
              <li><%= link_to 'Upload report',"#"  %></li> 
              <li> <%= link_to 'Learn More',"#"  %></li>
              <li> <%= link_to 'About us', "#" %></li>
              <li class="divider-vertical"></li>
              <li> <%=link_to "#{current_user.username}".html_safe, "#"%></li>
              <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li> <%= link_to 'Learn More', "#" %></li>
              <li> <%= link_to 'About us', "#" %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= content_for?(:title) ? yield(:title) : "ZLA" %></title>
<%= javascript_include_tag "application" %>
<%= stylesheet_link_tag    "application" %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= yield(:head) -%>
</head>
<body id="dt_example">
<%= render :partial => 'layouts/navBarLayout' %>
<div class="container">
  <%= render :partial => 'layouts/content' %>

</div> <!-- /container -->
</body>
</html>

app/views/reports/_form.html.erb
<%= form_for @report, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Report id", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rep_id, :class => 'text_field' %>
    </div>
  </div>
  <!-- <div class="control-group">
    <%#= f.label :grade, :class => 'control-label' %>
    <div class="controls">
      <%#= f.number_field :grade, :class => 'number_field' %>
    </div>
  </div> -->

   <p style="margin-left: 15%;">
    <%= f.file_field :file %>
  </p>
  <!-- <p> -->
    <%#= f.label :remote_file_url, "or file URL" %><br />
    <%#= f.text_field :remote_file_url %>
  <!-- </p> -->

  <div class="form-actions">
    <%= f.submit "Upload Report", :class => 'btn btn-primary' %>
    <%#= link_to t('.cancel', :default => t("helpers.links.cancel")),
                subjects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/reports/index.html.erb
<div class="well">
	<h2>Medical Reports</h2>
	<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique animi..</p>

	<div class="pull-right">
    <% if current_user.present? %>
        <%= link_to "Upload report", new_report_path, class: "btn btn-primary"%>
    <% end %>
    <%= link_to "download report", report_reports_path, class: "btn btn-success"%>
	</div><br/>
</div>


<div class="well">
	<h2>About Us</h2>
	<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique animi..</p>

	<div>
    <%= link_to "Read more", "#", class: "btn btn-success btn-mini"%>
</div><br/>
</div>

<div class="well">
	<h2>Contact Us</h2>
	<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique animi..</p>

	<div>
    <%= link_to "Read more", "#", class: "btn btn-success btn-mini"%>
</div><br/></div>

app/views/reports/new.html.erb
<div class="page-header">
  <h3>Upload new report</h3>
</div>
<div class="well">
<%= render :partial => 'form' %>
</div>

app/views/reports/report.html.erb
<%= form_for @report, url: download_reports_path,:html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Report Id:", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rep_id, :class => 'text_field' %>
    <%= f.submit "Download", :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>